server:
  port: 80

spring:
  application:
    name: cloud-order-service-feign
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode-true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: cloud
    password: 123456

eureka:
  client:
    #表示是否将自己注册进 EurekaServer, 默认为 true
    register-with-eureka: false
    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版

#设置Feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #建立连接后 从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #建立连接所用时间, 适用于网络状况正常情况下, 两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug