server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode-true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: cloud
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费占将要去访问的微服务名称（注册成功进 nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider